//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int book_id { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public string author { get; set; }
        public Nullable<System.DateTime> date_publication_university { get; set; }
        public Nullable<int> amount_pages { get; set; }
        public string url { get; set; }
    }
}
