//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int student_id { get; set; }
        public string name { get; set; }
        public Nullable<int> semester { get; set; }
        public string training { get; set; }
        public string performance { get; set; }
        public Nullable<System.DateTime> date_admission { get; set; }
    }
}
